<a href="https://colab.research.google.com/github/LaetitiaBeignon/Numerical-Analysis/blob/master/Lab6_Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Gaussian elimination

import scipy 
import scipy.linalg
import numpy as np
import copy

def linearsolver(A,b):
  n = len(A)
  M = A

  i = 0
  for x in M:
   x.append(b[i])
   i += 1


  for k in range(n):
   # first pivoting
   for i in range(k,n):
     if abs(M[i][k]) > abs(M[k][k]):
        M[k], M[i] = M[i],M[k]
     else:
        pass
   
   # Gaussian elimination in loop 
   for j in range(k+1,n):
       q = float(M[j][k]) / M[k][k]
       for m in range(k, n+1):
          # M_jm = M_jm - M_jk / M_kk *M_km
          M[j][m] -=  q * M[k][m]

  x = [0 for i in range(n)]       # x = [0, 0, .... , 0]

  # calculating x
  x[n-1] =float(M[n-1][n])/M[n-1][n-1]
  for i in range (n-1,-1,-1):
    z = 0
    for j in range(i+1,n):
        z = z  + float(M[i][j])*x[j]
    x[i] = float(M[i][n] - z)/M[i][i]
  return x


A11 = [[4, -1, 1], [2, 5, 2], [1, 2, 4]]
b11 = [8, 3, 11]

A22 = [[4, -1, 2], [2, 4, -1], [1, 1, -3]]
b22 = [9, -5, -9]

#First set of equation

A1 = copy.deepcopy(A11)
x = linearsolver(A1, b11)

print("Result with our linearsolver:")
print(np.array(A11)," * x = ",np.array(b11))
print("Solution:")
print(x)



x = scipy.linalg.solve(A11,b11)

print(" ")
print("Result with linalg.solve:")
print(np.array(A11)," * x = ",np.array(b11))
print("Solution:")
print(x)

print('\n')
#Second set of equation

A1 = copy.deepcopy(A22)
x = linearsolver(A1, b22)

print("Result with our linearsolver:")
print(np.array(A22)," * x = ",np.array(b22))
print("Solution:")
print(x)



x = scipy.linalg.solve(A22,b22)

print(" ")
print("Result with linalg.solve:")
print(np.array(A11)," * x = ",np.array(b22))
print("Solution:")
print(x)

Result with our linearsolver:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 8  3 11]
Solution:
[1.0, -1.0, 3.0]
 
Result with linalg.solve:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 8  3 11]
Solution:
[ 1. -1.  3.]


Result with our linearsolver:
[[ 4 -1  2]
 [ 2  4 -1]
 [ 1  1 -3]]  * x =  [ 9 -5 -9]
Solution:
[0.5849056603773586, -0.8113207547169813, 2.924528301886792]
 
Result with linalg.solve:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 9 -5 -9]
Solution:
[ 0.58490566 -0.81132075  2.9245283 ]
